#obj-y         += fingerprint/
#obj-$(CONFIG_PAX_PRINTER_MODULE) 		+= printer_module/
#obj-$(CONFIG_PAX_PRINTER_POWERCTL)		+= printer_powerctl/
#obj-y		+= printer_powerctl/
obj-$(CONFIG_PRINTER_POWER_MODULE)		+= printer_powerctl/
obj-$(CONFIG_PAX_POSVCOM_TEST)         += PosVcom/
